[package]
name = "started_02_echo_server"
version = "0.1.0"
authors = ["姚子建 <yaozijian110@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.1.21"